// Independent sequence player. All pixels come from the user's original renders.
// One shared bounded decoder cache replaces Readymag's per-widget eager preload.
export async function createMedia() {
 const manifest=await fetch(new URL('./assets/sequences.json',import.meta.url)).then(r=>{if(!r.ok)throw Error('Sequence manifest unavailable');return r.json();});
 const probe=manifest.find(s=>s.video&&s.page!=='main'&&s.page!=='korean_main');const supportsRanges=probe?await fetch(new URL(`./assets/video/${probe.key}.mp4`,import.meta.url),{method:"HEAD"}).then(r=>r.headers.get("Accept-Ranges")==="bytes").catch(()=>false):true;
 const byId=new Map();for(const s of manifest){byId.set(s.key,s);for(const id of s.ids)byId.set(id,s);}
 const cache=new Map(),pending=new Map(),queue=[],players=new Set();let working=0,tick=0,decodedBytes=0,loads=0,errors=0;
 const byteLimit=(navigator.deviceMemory&&navigator.deviceMemory<=4?56:100)*1024*1024;
 const key=(s,index)=>`${s.key}/${String(index+1).padStart(6,'0')}`;
 function trim(){const protect=new Set([...players].filter(p=>p.visible&&!p.dead).map(p=>p.wanted));const entries=[...cache.entries()].sort((a,b)=>a[1].used-b[1].used);for(const [k,e]of entries){if(decodedBytes<=byteLimit)break;if(protect.has(k))continue;cache.delete(k);decodedBytes-=e.bytes;e.bitmap.close();}}
 function pump(){while(working<4&&queue.length){queue.sort((a,b)=>a.priority-b.priority||b.order-a.order);const job=queue.shift();working++;(async()=>{try{const r=await fetch(new URL(job.k.startsWith('HD/')?'./assets/hd/'+job.k.slice(3)+'.jpg':'./assets/frames/'+job.k+'.webp',import.meta.url),{priority:job.priority===0?'high':'low'});if(!r.ok)throw Error(`Frame ${job.k}: ${r.status}`);const bitmap=await createImageBitmap(await r.blob());const entry={bitmap,bytes:bitmap.width*bitmap.height*4,used:++tick};cache.set(job.k,entry);decodedBytes+=entry.bytes;loads++;job.resolve(bitmap);trim();}catch(e){errors++;job.reject(e);}finally{pending.delete(job.k);working--;pump();}})();}}
 function get(s,index,priority=0,hd=false){index=Math.max(0,Math.min(s.frames-1,index));const k=(hd?'HD/':'')+key(s,index),cached=cache.get(k);if(cached){cached.used=++tick;return Promise.resolve(cached.bitmap);}const existing=pending.get(k);if(existing){existing.priority=Math.min(priority,existing.priority);return existing.promise;}const job={k,priority,order:++tick};job.promise=new Promise((resolve,reject)=>Object.assign(job,{resolve,reject}));pending.set(k,job);queue.push(job);pump();return job.promise;}
 function prefetch(s,index){if(!s||index<0||index>=s.frames||queue.length>9)return;get(s,index,2).catch(()=>{});}
 function attachImages(canvas,id){const sequence=byId.get(id);if(!sequence)throw Error('Unknown original sequence '+id);const player={canvas,sequence,index:0,lastIndex:-1,visible:false,dead:false,wanted:key(sequence,0),raf:0,drawn:null};players.add(player);const context=canvas.getContext('2d',{alpha:sequence.ext==='png',desynchronized:true});
  function draw(bitmap,index){if(player.dead||!player.visible||index!==player.index||!bitmap.width)return;const rect=canvas.getBoundingClientRect();if(!rect.width||!rect.height)return;const width=Math.max(1,Math.min(bitmap.width,Math.round(rect.width*Math.min(devicePixelRatio,1.5)))),height=Math.max(1,Math.round(width*rect.height/rect.width));if(canvas.width!==width||canvas.height!==height){canvas.width=width;canvas.height=height;}context.imageSmoothingEnabled=true;context.imageSmoothingQuality='high';const ratio=Math.max(width/bitmap.width,height/bitmap.height),dw=bitmap.width*ratio,dh=bitmap.height*ratio;context.clearRect(0,0,width,height);context.drawImage(bitmap,(width-dw)/2,(height-dh)/2,dw,dh);canvas.dataset.sequence=sequence.key;canvas.dataset.frame=String(index+1);canvas.dataset.ready='true';player.drawn=index;canvas.dispatchEvent(new CustomEvent('frame-ready',{detail:{sequence:sequence.key,frame:index+1}}));}
  function update(){player.raf=0;if(player.dead||!player.visible)return;const index=player.index;player.wanted=key(sequence,index);get(sequence,index,0).then(bitmap=>{draw(bitmap,index);const direction=Math.sign(index-player.lastIndex)||1;player.lastIndex=index;prefetch(sequence,index+direction);prefetch(sequence,index+2*direction);prefetch(sequence,index-direction);}).catch(e=>{canvas.dataset.error=e.message;});}
  function schedule(){if(!player.raf&&!player.dead)player.raf=requestAnimationFrame(update);}
  const observer=new IntersectionObserver(entries=>{player.visible=entries[0].isIntersecting;if(player.visible)schedule();},{rootMargin:'120px'});observer.observe(canvas);
  const resizeObserver=new ResizeObserver(()=>{player.drawn=null;schedule();});resizeObserver.observe(canvas);
  return {seek(p){const index=Math.max(0,Math.min(sequence.frames-1,Math.round(p*(sequence.frames-1))));if(index===player.index&&player.drawn===index)return;player.index=index;player.wanted=key(sequence,index);schedule();},frame(index){this.seek(index/Math.max(1,sequence.frames-1));},show(){player.visible=true;schedule();},info:sequence,destroy(){player.dead=true;cancelAnimationFrame(player.raf);observer.disconnect();resizeObserver.disconnect();players.delete(player);trim();}};
 }

 const videoCache=new Map();let videoRequests=0;
 function startVideo(r){if(r.started)return;r.started=true;videoRequests++;if(supportsRanges){r.video.src=r.src;return;}fetch(r.src).then(response=>{if(!response.ok)throw Error('Video unavailable');return response.blob();}).then(blob=>{if(r.disposed)return;r.blobURL=URL.createObjectURL(blob);r.video.src=r.blobURL;}).catch(error=>{r.error=error.message;errors++;});}

 function trimVideos(){const candidates=[...videoCache.entries()].filter(([,r])=>r.users===0).sort((a,b)=>a[1].used-b[1].used);for(const [k,r]of candidates){if(videoCache.size<=4)break;r.video.pause();r.video.removeAttribute('src');r.video.load();r.disposed=true;if(r.blobURL)URL.revokeObjectURL(r.blobURL);videoCache.delete(k);}}
 function acquire(s,load=true){let r=videoCache.get(s.key);if(!r){const video=document.createElement('video');video.muted=true;video.playsInline=true;video.preload='auto';r={video,users:0,used:++tick,src:new URL('./assets/video/'+s.key+'.mp4',import.meta.url).href,started:false};videoCache.set(s.key,r);}r.used=++tick;if(load)startVideo(r);trimVideos();return r;}
 function attachVideo(canvas,id){
  const sequence=byId.get(id),record=acquire(sequence,false),video=record.video;record.users++;
  const p={canvas,sequence,index:0,visible:false,dead:false,raf:0,drawn:-1,wanted:null};players.add(p);const ctx=canvas.getContext('2d',{alpha:false,desynchronized:true});
  function paintHD(bitmap,index){if(p.dead||!p.visible||index!==p.index||!bitmap.width)return;const r=canvas.getBoundingClientRect(),width=Math.min(bitmap.width,Math.round(r.width*devicePixelRatio)),height=Math.round(width*r.height/r.width);if(!width||!height)return;if(canvas.width!==width||canvas.height!==height){canvas.width=width;canvas.height=height;}ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high';const factor=Math.max(width/bitmap.width,height/bitmap.height),dw=bitmap.width*factor,dh=bitmap.height*factor;ctx.drawImage(bitmap,(width-dw)/2,(height-dh)/2,dw,dh);p.highRes=index;p.hdBitmap=bitmap;canvas.dataset.source='original-jpeg';canvas.dataset.pixelWidth=String(width);}

  function paint(){if(p.dead||!p.visible||video.readyState<2)return;const actual=Math.min(sequence.frames-1,Math.floor(video.currentTime*30+.0001));if(actual!==p.index)return;if(p.highRes===actual&&p.hdBitmap?.width){paintHD(p.hdBitmap,actual);return;}const r=canvas.getBoundingClientRect();if(!r.width||!r.height)return;const width=Math.max(1,Math.min(video.videoWidth,Math.round(r.width*Math.min(devicePixelRatio,2)))),height=Math.max(1,Math.round(width*r.height/r.width));if(canvas.width!==width||canvas.height!==height){canvas.width=width;canvas.height=height;}ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high';const scale=Math.max(width/video.videoWidth,height/video.videoHeight),w=video.videoWidth*scale,h=video.videoHeight*scale;ctx.drawImage(video,(width-w)/2,(height-h)/2,w,h);p.drawn=actual;canvas.dataset.source='video';canvas.dataset.pixelWidth=String(width);if(sequence.hdFrames?.includes(actual)&&!p.hdTimer){p.hdTimer=setTimeout(()=>{p.hdTimer=0;if(p.index!==actual||p.dead)return;p.wanted='HD/'+key(sequence,actual);get(sequence,actual,0,true).then(bitmap=>paintHD(bitmap,actual)).catch(()=>{});},160);}canvas.dataset.sequence=sequence.key;canvas.dataset.frame=String(actual+1);canvas.dataset.ready='true';canvas.dispatchEvent(new CustomEvent('frame-ready',{detail:{sequence:sequence.key,frame:actual+1}}));}
  function update(){p.raf=0;if(p.dead||!p.visible)return;if(!record.started)startVideo(record);if(video.readyState<1||video.seeking)return;const target=(p.index+.10)/30;const actual=Math.floor(video.currentTime*30+.0001);if(actual===p.index&&video.readyState>=2){paint();return;}try{video.currentTime=target;}catch(e){canvas.dataset.error=e.message;}}
  function schedule(){if(!p.raf&&!p.dead)p.raf=requestAnimationFrame(update);}
  const observer=new IntersectionObserver(entries=>{p.visible=entries[0].isIntersecting;if(p.visible)schedule();},{rootMargin:'120px'});observer.observe(canvas);const ro=new ResizeObserver(()=>{p.drawn=-1;schedule();});ro.observe(canvas);
  function ready(){paint();schedule();}function error(){canvas.dataset.error='Video '+sequence.key+' unavailable';errors++;}
  video.addEventListener('loadedmetadata',schedule);video.addEventListener('loadeddata',ready);video.addEventListener('seeked',ready);video.addEventListener('error',error);
  return {seek(value){const index=Math.round(Math.max(0,Math.min(1,value))*(sequence.frames-1));if(p.index===index&&p.drawn===index)return;if(p.index!==index){clearTimeout(p.hdTimer);p.hdTimer=0;p.wanted=null;}p.index=index;record.used=++tick;schedule();},frame(index){this.seek(index/Math.max(1,sequence.frames-1));},show(){p.visible=true;schedule();},info:sequence,destroy(){p.dead=true;clearTimeout(p.hdTimer);cancelAnimationFrame(p.raf);observer.disconnect();ro.disconnect();video.removeEventListener('loadedmetadata',schedule);video.removeEventListener('loadeddata',ready);video.removeEventListener('seeked',ready);video.removeEventListener('error',error);record.users--;players.delete(p);trimVideos();}};
 }
 function attach(canvas,id,{easing=false}={}){const s=byId.get(id);if(!s)throw Error('Unknown original sequence '+id);const raw=s.video?attachVideo(canvas,id):attachImages(canvas,id);if(!easing)return raw;let timer=0,lastTarget=0,lastCall=0;const max=s.frames-1;
  function seek(progress){const target=Math.max(0,Math.min(max,Math.round(progress*max))),now=Date.now(),elapsed=Math.max(1,now-lastCall),previous=canvas.dataset.sequence===s.key?Number(canvas.dataset.frame||1)-1:0;clearInterval(timer);timer=0;const distance=Math.min(Math.round(s.frames*.05),24,Math.round(Math.abs(lastTarget-target)*s.frames*2/(elapsed*elapsed)));lastCall=now;lastTarget=target;const start=target-Math.sign(target-previous)*Math.min(distance,Math.abs(target-previous)),remaining=target-start;raw.frame(start);if(!remaining)return;timer=setInterval(()=>{const t=Math.min(1,(Date.now()-now)/400),progress=1-Math.pow(1-t,3);raw.frame(start+Math.round(remaining*progress));if(t===1){clearInterval(timer);timer=0;}},16.66);}
  return {...raw,seek,frame(index){seek(index/Math.max(1,max));},destroy(){clearInterval(timer);raw.destroy();}};
 }

 return {attach,info:id=>byId.get(id),preload(id,index=0){const s=byId.get(id);if(s?.video)acquire(s);else if(s)prefetch(s,index);},stats(){return{rangeStreaming:supportsRanges,requests:loads+videoRequests,videoPlayers:videoCache.size,videos:[...videoCache].map(([key,r])=>({key,users:r.users,ready:r.video.readyState,network:r.video.networkState,seeking:r.video.seeking,time:r.video.currentTime,duration:r.video.duration,error:r.video.error?.message,buffered:Array.from({length:r.video.buffered.length},(_,i)=>[r.video.buffered.start(i),r.video.buffered.end(i)])})),errors,cacheFrames:cache.size,decodedMB:Math.round(decodedBytes/1048576),pending:pending.size,players:players.size};},destroy(){for(const p of players){p.dead=true;cancelAnimationFrame(p.raf);}players.clear();for(const e of cache.values())e.bitmap.close();cache.clear();decodedBytes=0;}};
}
