const clamp=(n,a=0,b=1)=>Math.max(a,Math.min(b,n));
function easeBoth(t){t=clamp(t);let low=0,high=1,u=t;for(let i=0;i<14;i++){u=(low+high)/2;const x=3*(1-u)*(1-u)*u*.42+3*(1-u)*u*u*.58+u*u*u;if(x<t)low=u;else high=u;}return 3*(1-u)*u*u+u*u*u;}

export async function mountViewer(container,{media,onHome,startPage=0}={}){
 const data=await fetch(new URL('./assets/tour.json',import.meta.url)).then(r=>r.json());
 const root=document.createElement('section');root.className='original-tour';root.innerHTML='<div class="original-stage"><canvas aria-label="원본 3D 전시 렌더"></canvas></div><a href="#home" class="original-home">Go to main page</a><div class="original-ending"></div><div class="original-tour-space"></div><div class="sr-only original-description" aria-live="polite"></div>';container.replaceChildren(root);
 const canvas=root.querySelector('canvas'),stage=root.querySelector('.original-stage'),ending=root.querySelector('.original-ending'),space=root.querySelector('.original-tour-space'),home=root.querySelector('.original-home'),description=root.querySelector('.original-description');
 let scale=1,bounds=[],total=0,activePage=-1,activeWidget=null,player=null,raf=0,dead=false,lastY=0,manualScale=false;
 const endItems=[];
 function fit(){const previousPage=activePage,previousLocal=previousPage>=0&&bounds[previousPage]?scrollY/scale-bounds[previousPage].start:0;scale=innerWidth/1024;let offset=0;const vh=innerHeight/scale;bounds=data.pages.map((p,i)=>{const last=p.widgets[p.widgets.length-1];const natural=p.height-vh,minEnd=last.scrollDelay+(last.frames-1)*20;const length=Math.max(natural>=minEnd?natural:minEnd+80,i===15&&scale<.8?4260:0);const b={start:offset,end:offset+length,length};offset+=length;return b;});total=offset;space.style.height=`${total*scale+innerHeight}px`;root.style.setProperty('--design-scale',scale);home.style.top=`${23*scale}px`;home.style.right=`${33*scale}px`;home.style.fontSize=`${12*scale}px`;home.style.lineHeight=`${12*scale}px`;ending.style.width=`1024px`;if(activeWidget){stage.style.width=`${activeWidget.w*scale}px`;stage.style.height=`${activeWidget.h*scale}px`;stage.style.left=`calc(50% + ${(activeWidget.x-activeWidget.w/2)*scale}px)`;stage.style.top=`calc(50% + ${(activeWidget.y-activeWidget.h/2)*scale}px)`;}if(previousPage>=0)window.scrollTo(0,(bounds[previousPage].start+Math.min(previousLocal,bounds[previousPage].length-1))*scale);schedule();}
 function makeEnding(){ending.replaceChildren();for(const w of data.ending){if(w.type==='text'){const el=document.createElement('div');el.className='original-end-text';el.dataset.y=w.y;el.style.cssText=`position:absolute;left:${w.x}px;top:${w.y}px;width:${w.w}px;font-family:Arial;font-weight:400;font-size:54px;line-height:63px;letter-spacing:-1.5px;color:#000;white-space:pre-line;`;el.style.textAlign=w.blocksMeta?.[0]?.data?.align==='align-right'?'right':'left';el.textContent=w.blocks.map(b=>b.text).join('\n');ending.append(el);endItems.push({w,el});}else if(w.type==='picture'){const el=document.createElement('img');el.src=w.local;el.alt='';el.style.cssText=`position:absolute;left:${w.x}px;top:${w.y}px;width:${w.w}px;height:${w.h}px;object-fit:cover;`;el.loading='lazy';el.style.zIndex=w.z||1;if(w.clickLink){el.style.pointerEvents='auto';el.style.cursor='pointer';el.setAttribute('role','link');el.setAttribute('tabindex','0');el.setAttribute('aria-label','메인으로 돌아가기');el.onclick=()=>onHome?.();el.onkeydown=e=>{if(e.key==='Enter')onHome?.();};}ending.append(el);endItems.push({w,el,started:false});}}}
 makeEnding();
 function draw(){raf=0;if(dead)return;const logical=scrollY/scale;let index=bounds.findIndex(b=>logical<b.end);if(index<0)index=data.pages.length-1;const p=data.pages[index],local=Math.max(0,logical-bounds[index].start);if(index!==activePage){activePage=index;root.dataset.page=p.uri;description.textContent=p.description||p.uri;}
  const widget=[...p.widgets].reverse().find(w=>local>=w.scrollDelay)||p.widgets[0];
  if(!activeWidget||activeWidget.id!==widget.id){player?.destroy();activeWidget=widget;player=media.attach(canvas,widget.id,{easing:true});player.show();stage.style.width=`${widget.w*scale}px`;stage.style.height=`${widget.h*scale}px`;stage.style.left=`calc(50% + ${(widget.x-widget.w/2)*scale}px)`;stage.style.top=`calc(50% + ${(widget.y-widget.h/2)*scale}px)`;const n=p.widgets.indexOf(widget);const nxt=p.widgets[n+1]||data.pages[index+1]?.widgets[0];if(nxt)media.preload(nxt.id,0);}
  const frame=Math.round((local-widget.scrollDelay)*widget.scrollSpeed/10);player.frame(clamp(frame,0,widget.frames-1));
  const isLast=index===15,virtualEndHeight=scale<.8?640:innerHeight/scale,endShift=scale<.8?Math.max(0,(innerHeight/scale-640)/2):0;const fade=isLast?easeBoth((local-3800)/484):0;stage.style.opacity=isLast&&local>=4000?'0':'1';stage.style.setProperty('--end-wash',fade);stage.style.setProperty('--wash-bottom',isLast?`${17.5*scale}px`:'0px');root.style.backgroundColor='#'+(p.background||'ffffff');home.style.visibility=isLast&&local>=3900?'hidden':'visible';ending.style.display=isLast?'block':'none';ending.style.transform=`translateY(${((bounds[index].start+endShift)*scale)-scrollY}px) scale(${scale})`;ending.style.opacity=isLast?'1':'0';
  if(isLast){const vh=virtualEndHeight;for(const item of endItems){const {w,el}=item;if(w.type==='text'){const delta=clamp(local-(w.y-vh/2+165),0,484);el.style.transform='translateY('+ (delta<=32?-delta:delta-64)+'px)';el.style.opacity=clamp(delta/32);}else if(!item.started&&w.y-local<vh){item.started=true;const steps=w.animation.find(a=>a.type==='load').steps;const sum=steps.reduce((n,a)=>n+(a.duration||0),0);let elapsed=0;const frames=[{transform:'translate(0px,0px) rotate(0deg)',offset:0,easing:'cubic-bezier(.42,0,1,1)'}];let rotate=0;for(const step of steps){elapsed+=step.duration||0;rotate=step.use_rotate?step.rotate:rotate;frames.push({transform:'translate('+(step.dx||0)+'px,'+(step.dy||0)+'px) rotate('+rotate+'deg)',offset:elapsed/sum,easing:'ease-in-out'});}el.animate(frames,{duration:sum*1000,delay:(steps[0].delay||0)*1000,fill:'both'});}}}

  canvas.dataset.logical=local.toFixed(2);canvas.dataset.page=p.uri;root.dataset.logical=logical.toFixed(2);lastY=scrollY;
 }
 function schedule(){if(!raf&&!dead)raf=requestAnimationFrame(draw);}
 function jump(i){i=clamp(i,0,data.pages.length-1);window.scrollTo(0,Math.ceil(bounds[i].start*scale)+1);schedule();}
 home.onclick=e=>{e.preventDefault();onHome?.();};
 function keys(e){if(/INPUT|TEXTAREA|SELECT/.test(document.activeElement?.tagName))return;if(e.key==='ArrowRight'){e.preventDefault();jump(activePage+1);}if(e.key==='ArrowLeft'){e.preventDefault();jump(activePage-1);}if(e.key==='Escape')onHome?.();}
 window.addEventListener('scroll',schedule,{passive:true});window.addEventListener('resize',fit,{passive:true});window.addEventListener('keydown',keys);fit();jump(startPage);
 return {jump,stats:()=>({page:activePage+1,logical:scrollY/scale,frame:canvas.dataset.frame,sequence:canvas.dataset.sequence,...media.stats()}),destroy(){dead=true;cancelAnimationFrame(raf);player?.destroy();window.removeEventListener('scroll',schedule);window.removeEventListener('resize',fit);window.removeEventListener('keydown',keys);root.remove();}};
}
